### ISSUE TITLE
ld: warning: direct access in function

### ISSUE THREAD

**Issue by ni4** [rnpgp/sexp#28]
Got the following warning while compiling sexp on macOS with CLang 12:

`ld: warning: direct access in function 'std::__1::__shared_ptr_pointer<sexp::sexp_string_t*, std::__1::default_delete<sexp::sexp_string_t>, std::__1::allocator<sexp::sexp_string_t> >::__get_deleter(std::type_info const&) const' from file '../lib/librnp.a(key_store_g10.cpp.o)' to global weak symbol 'typeinfo for std::__1::default_delete<sexp::sexp_string_t>' from file '../libsexp/libsexp.a(sexp-input.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.`

**Comment by maxirmx** [comment]
I believe it has been fixed
https://github.com/rnpgp/sexp/commit/6439815878ece8fce8c5bd1f28a51e40770d55e2
