### ISSUE TITLE
warning: format specifies type 'unsigned long' but the argument has type 'uint64_t'

### ISSUE THREAD

**Issue by ni4** [rnpgp/sexp#29]
Building with CLang 12.0 under the macOS gives the following warning:

`libsexp/src/sexp-output.cpp:190:14: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
             n); // since itoa is not a part of any standard`

**Comment by maxirmx** [comment]
I believe it has been fixed
https://github.com/rnpgp/sexp/commit/8e787f151ebf97f0fde9b4634bb850bcf13cb680
