### ISSUE TITLE
Please clarify License

### ISSUE THREAD

**Issue by remicollet** [rnpgp/sexp#33]
According to the LICENSE and README.md files, this is **MIT**

According to sources headers, this is **BSD-2-Clause**

**Comment by maxirmx** [comment]
I believe this is the right license: https://github.com/rnpgp/sexp/blob/main/LICENSE.md
@ronaldtse  Could you please confirm ?

**Comment by ronaldtse** [comment]
@remicollet @maxirmx yes this library is under the MIT license.

@maxirmx can we update the source headers to reflect this? Thanks!
